### ISSUE TITLE
Error #01: assignment to entry in nil map when trying to set headers

### ISSUE THREAD

**Issue by AddaxT** [devopsfaith/krakend-lua#8]
Hi,

Currently we are using Krakend latest docker image and we are using krakend-lua plugin to transform the request and response, with the request everything seems to be fine, but when we try to set response header we are getting the error below:

<p>Error #01: assignment to entry in nil map<br>
goroutine 83 [running]:<br>
github.com/yuin/gopher-lua.(*LState).PCall.func1(0x22b7ec0, 0xc000160780, 0xc0009170e0, 0x0, 0x0, 0x0)<br>
        /go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20190206043414-8bfc7677f583/state.go:1634 +0x601
panic(0x1f747e0, 0x251a0e0)<br>
        /usr/local/go/src/runtime/panic.go:967 +0x15d<br>
github.com/devopsfaith/krakend-lua/proxy.(*response).headers(0xc0005a80b0, 0xc000ecaa60, 0x1, 0xc000ecaa60)
        /go/pkg/mod/github.com/devopsfaith/krakend-lua@v1.1.0/proxy/response.go:86 +0x17c<br></p>

The error can be reproduced using the setup below in the post section of the plugin configuration in any backend:

`"post": "local resp = response.load(); resp:headers('Content-Type', 'application/json');"`

**Comment by AddaxT** [comment]
This is fixed after setting the encoding to no-op.
